export const ActionTypes = {
  // Set types
  SET_USERS: "SET_USERS",
  SET_USER: "SET_USER",
  SET_SUB_CATEGORY: "SET_SUB_CATEGORY",
  SET_CATEGORY: "SET_CATEGORY",
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_INFO_FIELDS: "SET_INFO_FIELDS",
  SET_ACCOUNT_FIELDS: "SET_ACCOUNT_FIELDS",

  // Update types
  UPDATE_USERS: "UPDATE_USERS",
  UPDATE_USER: "UPDATE_USER",

  // Delete types
  DELETE_USER: "DELETE_USER",

  // Remove types
  REMOVE_USER: "REMOVE_USER",
};
